import streamlit as st 
import os

def sidebar():
    with st.sidebar:
        st.write("""
                 ## ✍️ Blog Post Generator"
                 
                 ### How to use
                 
                1. Enter the number of web references you want to use. (Max 10).
                2. Enter your [OpenAI API key](https://platform.openai.com/api-keys) below.
                3. Enter the keyword you want to generate a blog post for.
                4. Click on the "Generate blog post" button.
                 
                 """
                 )
                        
        openai_api_key = st.text_input(
            label="OpenAI API Key",
            type="password"
            )
        
        os.environ['OPENAI_API_KEY'] = openai_api_key

        st.divider()

        st.write("""
        ### About

        ✍️ Blog Post Generator allows you to generate an SEO optimised blog post from keywords. 
        It uses web references from top ranking articles to generate your blog post. 
        It also allows you to specify a number of web links to use. 
        It only allows a maximum of 10.

        This agent is a work in progress and you can contribute to it on [Github](https://github.com/jordan-jakisa/blog_post_writer) 
        with your feedback and suggestions.

        Made with ❤️ from Uganda by [jordan-jakisa](https://github.com/jordan-jakisa)
        """)

        st.divider()

        st.write("""
        ### FAQs

        #### How does it work?
        The Blog Post Generator uses web references from top ranking articles to generate your blog post.

        #### Is the information generated by the agent accurate?
        The agent generates information based on the web references provided. It is recommended to verify the information generated.

        #### How many web references can I use?
        You can use a maximum of 10 web references.

        #### How do I get an OpenAI API key?
        You can get an OpenAI API key by signing up at [OpenAI](https://platform.openai.com/account/api-keys).

        #### How do I contribute to the project?
        You can contribute to the project on [Github](https://github.com/jordan-jakisa/blog_post_writer)

        """)

        st.divider()